import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Profil from './../components/Profil';
import { ChangeEvent, useMemo, useState } from 'react';
import TextArea from '../components/TextArea';
import Modal from '../components/Modal';

export default function Home() {
	const [content, setContent] = useState('');

	const textAreaMemo = useMemo(() => {
		return (
			<TextArea
				cross
				value={content}
				onChange={(e: ChangeEvent<HTMLTextAreaElement>) => {
					setContent(e.target.value);
				}}
			/>
		);
	}, [content]);

	const modalMemo = useMemo(() => {
		return <Modal title="Create a post" type="post" />;
	}, []);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Profil fullWidth />

				{modalMemo}
			</main>
			{textAreaMemo}

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
